---
title: "Agentic and Communal Final Graphics"
author: "Robert W. Walker"
format: html
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning=FALSE, message=FALSE, fig.height=6, fig.retina=3, dev="CairoJPEG")
```


The data generation script is a separate file.  The code is here and the log is on the relevant github repository.

```{r, echo=TRUE, eval=FALSE}
sink("./CleanTestResultsFinal-M1-10-2022.txt")
set.seed(103050701)
library(tidyverse)
library(readxl)
EMData <- read_excel("Study 1 Final Version.xlsx", skip = 1)
EMData.Anonymous <- read_excel("Study 1 Final Version.xlsx", skip = 2, col_names = FALSE)
Keys <- data.frame(cbind(names(EMData),names(EMData.Anonymous)))
names(EMData)[[80]]
table(EMData.Anonymous$...80)
names(EMData)[[81]]
table(EMData.Anonymous$...81)
names(EMData)[[84]]
table(EMData.Anonymous$...84)
names(EMData.Anonymous)[c(80,81,84)] <- c("Unselfish","Others.Opinions","Others.Interests")
library(MCMCpack)
Communal.Behavior <- MCMCordfactanal(~Unselfish+Others.Opinions+Others.Interests, data=EMData.Anonymous, factors=1, burnin=500000, mcmc=10000000, thin=1000, tune=1.3, store.scores=TRUE, L0=0.5, verbose = 500000)
names(EMData)[[76]]
table(EMData.Anonymous$...76)
names(EMData)[[77]]
table(EMData.Anonymous$...77)
names(EMData)[[78]]
table(EMData.Anonymous$...78)
names(EMData)[[79]]
table(EMData.Anonymous$...79)
names(EMData.Anonymous)[c(76:79)] <- c("Leader","Individual.Success","Assertive","Strong.Opinions")
Agentic.Behavior <- MCMCordfactanal(~Leader+Individual.Success+Assertive+Strong.Opinions, data=EMData.Anonymous, factors=1, burnin=500000, mcmc=10000000, thin=1000, tune=1.4, store.scores=TRUE, L0=0.5, verbose = 500000)
names(EMData)[[13]]
table(EMData.Anonymous$...13)
names(EMData)[[14]]
table(EMData.Anonymous$...14)
names(EMData)[[15]]
table(EMData.Anonymous$...15)
names(EMData.Anonymous)[c(13,14,15)] <- c("Encourage.Starts","Reassure","Give.Confidence")
Mentoring <- MCMCordfactanal(~Encourage.Starts+Reassure+Give.Confidence, data=EMData.Anonymous, factors=1, burnin=500000, mcmc=10000000, thin=1000, tune=1.5, store.scores=TRUE, L0=0.5, verbose = 500000)
names(EMData)[[37]]
table(EMData.Anonymous$...37)
names(EMData)[[38]]
table(EMData.Anonymous$...38)
names(EMData)[[39]]
table(EMData.Anonymous$...39)
names(EMData.Anonymous)[c(37,38,39)] <- c("Respect","Understanding","Influence")
Social.Influence <- MCMCordfactanal(~Respect+Understanding+Influence, data=EMData.Anonymous, factors=1, burnin=500000, mcmc=10000000, thin=1000, tune=2.3, L0=0.5, store.scores=TRUE, verbose = 500000)
save.image("CleanTestResultsFinal-M1-10-2022.RData")
```

The aforemention transforms the names in the datasets of interest.  Github has a limit of 25MB file sizes necessitating a split of the total file into four parts loaded below from Github.

```{r}
load(url("https://github.com/robertwwalker/EMAC-Samples/raw/main/SI.RData"))
load(url("https://github.com/robertwwalker/EMAC-Samples/raw/main/Communal.RData"))
load(url("https://github.com/robertwwalker/EMAC-Samples/raw/main/Agentic-Plus.RData"))
load(url("https://github.com/robertwwalker/EMAC-Samples/raw/main/Mentoring.RData"))
```


Let's now first build a table of the relevant acceptance rates.

```{r}
library(gt)
AR.Table <- data.frame(Group = c(rep("Communal", 3), rep("Agentic",4), rep("Mentoring", 3), rep("Social Influence", 3)), Var = c("You are expected to be unselfish.", "In your interactions with others you are expected to consider others opinions over your own", "Your community expects you to put others interests ahead of your own", "People in the community expect you to be a leader", "Your community encourages you to achieve individual success", "You are expected to be assertive in your interactions with others", "You are expected to have strong opinions","Encourage entrepreneurs to start businesses", "Reassure other entrepreneurs when things are not going well","Help other entrepreneurs have confidence they can succeed", "The respect you have in the community helps your business","Your understanding of the community helps your business","Your influence in the community helps your business"),
`Acceptance Rate` = c(0.25, 0.27,
0.26,
0.19,
0.29,
0.33,
0.25,
0.27,
0.22, 
0.22,
0.21,
0.26,
0.22))
Table <- AR.Table %>% gt(rowname_col = "Var", groupname_col = "Group") %>% tab_header("Metropolis-Hastings Acceptance Rates for Ordered Factor Analysis")
Table
```

